#include "wh3/identity_gate.hpp"
#include <atomic>
#include <future>
#include <iostream>
#include <limits>
#include <random>
#include <sstream>
#include <stdexcept>
#include <thread>
#include <utility>
using namespace wh3;
#define CHECK(expr) do { if(!(expr)){std::ostringstream s;s<<__FILE__<<":"<<__LINE__<<" " #expr;throw std::runtime_error(s.str());} } while(false)
template<class T>T must(Result<T> r) {CHECK(r.error==Error::Ok);return r.value;}
Order move(Unit u,bool q=false) {Order o;o.recipient=u;o.kind=Kind::Move;o.queued=q;o.x=10;o.y=0;o.z=20;return o;}
Order attack(Unit u,bool q=false) {Order o;o.recipient=u;o.kind=Kind::Attack;o.queued=q;o.target_uid=1008;o.target_root=0x15a0b18e0ULL;o.raw70=1;return o;}
Order halt(Unit u) {Order o;o.recipient=u;o.kind=Kind::Halt;o.halt_flags=1;return o;}
struct F {
    IdentityGate c;Id epoch;Unit u;Stream s;View v;Id offset=0;int calls=0;
    explicit F(Limits l={}):c(l),epoch(must(c.begin_battle())),u(must(c.register_unit(1002,0x12340000))),s(must(c.open_stream(0x2000,0x5000))),v(must(c.bind_view(s,0x3000,0,0,0x5000))) {CHECK(c.set_issue_enabled(true)==Error::Ok);}
    Issue issue(Unit x,Kind k=Kind::Move,bool q=false) {return must(c.make_issue(k,q,{must(c.snapshot(x))}));}
    PacketKey bind(Issue i,Kind k=Kind::Move,bool q=false,std::vector<Unit> us={}) {
        if(us.empty())us={u};auto scope=c.own_scope(i);auto p=must(c.commit_packet(s,offset,16,k,q,us));offset+=16;return p;
    }
    PacketKey own(Kind k=Kind::Move,bool q=false) {return bind(issue(u,k,q),k,q);}
    DispatchResult send(PacketKey k,Order o,NativeOutcome n={true,Id(0)}) {return c.dispatch_owned(k,o,[&]{++calls;return n;});}
    Event ext(Order o,NativeOutcome n={true,Id(7)}) {return must(c.observe_external(o,n));}
    Page page(Id after=0,std::size_t count=64) {return must(c.read(epoch,after,count));}
};
int main(){int pass=0,fail=0;
 auto test=[&](const char* name,auto fn){try{fn();std::cout<<"PASS "<<name<<"\n";++pass;}catch(const std::exception& e){std::cout<<"FAIL "<<name<<" : "<<e.what()<<"\n";++fail;}};
 test("default is disabled, explicit battle required",[]{IdentityGate c;CHECK(!c.issue_enabled());CHECK(!c.register_unit(1,1));must(c.begin_battle());CHECK(!c.issue_enabled());CHECK(!c.make_issue(Kind::Move,false,{}));});
 test("duplicate battle start is rejected",[]{F f;CHECK(!f.c.begin_battle());});
 test("registered unit lifetime is independent of reused pointer",[]{F f;auto old=f.u;CHECK(f.c.retire_unit(old)==Error::Ok);auto now=must(f.c.register_unit(old.uid,0x12340000));CHECK(now!=old);CHECK(!f.c.snapshot(old));CHECK(must(f.c.snapshot(now)).revision==0);});
 test("duplicate unit registration cannot reset revision",[]{F f;f.ext(move(f.u));CHECK(!f.c.register_unit(1002,0x12340000));CHECK(must(f.c.snapshot(f.u)).revision==1);});
 test("unit uid zero is not confused with absent unit",[]{F f;auto u=must(f.c.register_unit(0,0x5000));CHECK(f.ext(move(u)).order.recipient.uid==0);});
 test("u32 codec exact endpoints and float32 boundary",[]{for(Id x:{Id(0),Id(16777215),Id(16777216),Id(16777217),Id(0xffffffff)})CHECK(must(parse_id(format_id(x)))==x);});
 test("u32 codec rejects malformed and overflow",[]{for(auto s:{"","00","01","-1","+1"," 1","1 ","0x1","1.0","4294967296","99999999999","NaN"})CHECK(!parse_id(s));});
 test("native seq zero remains valid",[]{F f;auto k=f.own();CHECK(f.send(k,move(f.u)).status==Status::Accepted);auto e=f.page().events.back();CHECK(e.engine_seq.has_value()&&*e.engine_seq==0);CHECK(e.source==Source::OurController);CHECK(e.script_issue_id!=0);});
 test("same target external cannot acquire controller token",[]{F f;auto k=f.own();auto x=f.ext(move(f.u));CHECK(x.source==Source::Unknown&&x.script_issue_id==0);CHECK(f.send(k,move(f.u)).status==Status::RejectedStale);CHECK(f.calls==0);});
 test("append changes revision and invalidates old decision",[]{F f;auto k=f.own();f.ext(move(f.u,true));CHECK(f.send(k,move(f.u)).status==Status::RejectedStale);CHECK(f.calls==0);});
 test("attack replace invalidates old move",[]{F f;auto k=f.own();f.ext(attack(f.u));CHECK(f.send(k,move(f.u)).status==Status::RejectedStale);CHECK(f.calls==0);});
 test("halt without slot invalidates pending move",[]{F f;auto k=f.own();auto e=f.ext(halt(f.u),{true,{}});CHECK(!e.engine_seq);CHECK(e.revision==1);CHECK(f.send(k,move(f.u)).status==Status::RejectedStale);CHECK(f.calls==0);});
 test("native rejection has no revision or phantom sequence",[]{F f;auto k=f.own();CHECK(f.send(k,move(f.u),{false,{}}).status==Status::NativeRejected);CHECK(must(f.c.snapshot(f.u)).revision==0);CHECK(!f.page().events[0].engine_seq);});
 test("accepted no slot recorded explicitly",[]{F f;auto k=f.own();CHECK(f.send(k,move(f.u),{true,{}}).status==Status::AcceptedNoSlot);CHECK(must(f.c.snapshot(f.u)).revision==1);CHECK(!f.page().events[0].engine_seq);});
 test("source proof is not payload matching",[]{F f;auto i=f.issue(f.u);PacketKey owned,unknown;{auto s=f.c.own_scope(i);{auto e=f.c.external_scope();unknown=must(f.c.commit_packet(f.s,0,16,Kind::Move,false,{f.u}));}owned=must(f.c.commit_packet(f.s,16,16,Kind::Move,false,{f.u}));}CHECK(must(f.c.packet_source(unknown))==Source::Unknown);CHECK(must(f.c.packet_source(owned))==Source::OurController);});
 test("no producer scope remains external",[]{F f;auto k=must(f.c.commit_packet(f.s,0,16,Kind::Move,false,{f.u}));CHECK(must(f.c.packet_source(k))==Source::Unknown);CHECK(f.send(k,move(f.u)).status==Status::RejectedUnbound);auto e=f.ext(move(f.u));CHECK(e.source==Source::Unknown);});
 test("nested owned scopes restore parent",[]{F f;auto a=f.issue(f.u),b=f.issue(f.u);PacketKey ka,kb;{auto sa=f.c.own_scope(a);{auto sb=f.c.own_scope(b);kb=must(f.c.commit_packet(f.s,16,16,Kind::Move,false,{f.u}));}ka=must(f.c.commit_packet(f.s,0,16,Kind::Move,false,{f.u}));}CHECK(f.send(ka,move(f.u)).status==Status::Accepted);CHECK(f.send(kb,move(f.u)).status==Status::RejectedStale);});
 test("scope restored during C++ exception unwind",[]{F f;auto a=f.issue(f.u);try{auto sa=f.c.own_scope(a);throw std::runtime_error("fixture");}catch(const std::runtime_error&){}auto k=must(f.c.commit_packet(f.s,0,16,Kind::Move,false,{f.u}));CHECK(must(f.c.packet_source(k))==Source::Unknown);});
 test("producer TLS does not leak to another thread",[]{F f;auto i=f.issue(f.u);PacketKey k;{auto scope=f.c.own_scope(i);std::thread t([&]{k=must(f.c.commit_packet(f.s,0,16,Kind::Move,false,{f.u}));});t.join();}CHECK(must(f.c.packet_source(k))==Source::Unknown);});
 test("producer scope from another core is not reused",[]{F f,g;auto i=f.issue(f.u);auto scope=f.c.own_scope(i);auto k=must(g.c.commit_packet(g.s,0,16,Kind::Move,false,{g.u}));CHECK(must(g.c.packet_source(k))==Source::Unknown);});
 test("one issue cannot bind two packets",[]{F f;auto i=f.issue(f.u);f.bind(i);auto scope=f.c.own_scope(i);CHECK(!f.c.commit_packet(f.s,16,16,Kind::Move,false,{f.u}));CHECK(!f.c.issue_enabled());});
 test("scope cannot bind wrong kind",[]{F f;auto i=f.issue(f.u);auto scope=f.c.own_scope(i);CHECK(!f.c.commit_packet(f.s,0,16,Kind::Attack,false,{f.u}));});
 test("scope cannot bind wrong queued bit",[]{F f;auto i=f.issue(f.u);auto scope=f.c.own_scope(i);CHECK(!f.c.commit_packet(f.s,0,16,Kind::Move,true,{f.u}));});
 test("scope cannot bind wrong recipient",[]{F f;auto u=must(f.c.register_unit(1003,0x4000));auto i=f.issue(f.u);auto scope=f.c.own_scope(i);CHECK(!f.c.commit_packet(f.s,0,16,Kind::Move,false,{u}));});
 test("duplicate recipient cannot fake batch",[]{F f;auto sn=must(f.c.snapshot(f.u));CHECK(!f.c.make_issue(Kind::Move,false,{sn,sn}));CHECK(!f.c.commit_packet(f.s,0,16,Kind::Move,false,{f.u,f.u}));});
 test("consumer copy mapped to producer offsets exactly",[]{F f;auto k=f.own();auto view=must(f.c.bind_view(f.s,0x9999,100,0,128));CHECK(must(f.c.resolve(view,100,16))==k);CHECK(f.send(must(f.c.resolve(view,100,16)),move(f.u)).status==Status::Accepted);});
 test("wrong length or offset never fuzzy-matches",[]{F f;f.own();CHECK(!f.c.resolve(f.v,0,15));CHECK(!f.c.resolve(f.v,1,16));CHECK(!f.c.resolve(f.v,0,17));});
 test("consumer range is checked before translation",[]{F f;auto view=must(f.c.bind_view(f.s,0x9999,100,0,32));CHECK(!f.c.resolve(view,99,1));CHECK(!f.c.resolve(view,120,16));CHECK(!f.c.resolve(view,100,0));});
 test("address reuse requires explicit new stream generation",[]{F f;auto a=f.own();auto s2=must(f.c.open_stream(0x2000,0x5000));auto v2=must(f.c.bind_view(s2,0x3000,0,0,0x5000));auto i=f.issue(f.u);PacketKey b;{auto scope=f.c.own_scope(i);b=must(f.c.commit_packet(s2,0,16,Kind::Move,false,{f.u}));}CHECK(a.generation!=b.generation);CHECK(must(f.c.resolve(f.v,0,16))==a);CHECK(must(f.c.resolve(v2,0,16))==b);});
 test("retired stream invalidates its views and keys",[]{F f;auto k=f.own();CHECK(f.c.retire_stream(f.s)==Error::Ok);CHECK(!f.c.resolve(f.v,0,16));CHECK(f.send(k,move(f.u)).status==Status::RejectedUnbound);CHECK(f.calls==0);});
 test("retired reader id cannot be silently reused",[]{F f;f.own();CHECK(f.c.retire_view(f.v)==Error::Ok);auto now=must(f.c.bind_view(f.s,0x3000,0,0,0x5000));CHECK(now.id!=f.v.id);CHECK(!f.c.resolve(f.v,0,16));CHECK(f.c.resolve(now,0,16));});
 test("offset wrap is rejected, not guessed as generation",[]{F f;CHECK(!f.c.commit_packet(f.s,0xfffffff0,32,Kind::Move,false,{f.u}));CHECK(!f.c.bind_view(f.s,0x4444,0xfffffff0,0,32));});
 test("overlapping packet span latches fault",[]{F f;f.own();CHECK(!f.c.commit_packet(f.s,8,16,Kind::Move,false,{f.u}));CHECK(f.c.fault()==Error::BindingMismatch);});
 test("adjacent spans remain distinct",[]{F f;auto a=f.own(),b=f.own();CHECK(!(a==b));CHECK(f.c.resolve(f.v,16,16));});
 test("packet consumption is one-shot per recipient",[]{F f;auto k=f.own();CHECK(f.send(k,move(f.u)).status==Status::Accepted);CHECK(f.send(k,move(f.u)).status==Status::RejectedDuplicate);CHECK(f.calls==1);});
 test("native-rejected attempt cannot be replayed",[]{F f;auto k=f.own();f.send(k,move(f.u),{false,{}});CHECK(f.send(k,move(f.u)).status==Status::RejectedDuplicate);CHECK(f.calls==1);});
 test("cancelled owned packet cannot call original",[]{F f;auto i=f.issue(f.u);auto k=f.bind(i);CHECK(f.c.cancel_issue(i)==Error::Ok);CHECK(f.send(k,move(f.u)).status==Status::RejectedCancelled);CHECK(f.calls==0);});
 test("cancelled issue cannot bind later",[]{F f;auto i=f.issue(f.u);CHECK(f.c.cancel_issue(i)==Error::Ok);auto scope=f.c.own_scope(i);CHECK(!f.c.commit_packet(f.s,0,16,Kind::Move,false,{f.u}));});
 test("metadata tampering rejected before native",[]{F f;auto k=f.own();CHECK(f.send(k,move(f.u,true)).status==Status::RejectedMetadata);CHECK(f.calls==0);CHECK(f.send(k,move(f.u)).status==Status::RejectedDuplicate);});
 test("retired unit invalidates old issue even same UID/root",[]{F f;auto k=f.own();auto old=f.u;f.c.retire_unit(old);auto now=must(f.c.register_unit(1002,0x12340000));CHECK(f.send(k,move(now)).status==Status::RejectedUnitLifetime);CHECK(f.send(k,move(old)).status==Status::RejectedUnitLifetime);CHECK(f.calls==0);});
 test("batch has shared command and distinct final geometry",[]{F f;auto u2=must(f.c.register_unit(1003,0x5555));auto i=must(f.c.make_issue(Kind::Move,false,{must(f.c.snapshot(f.u)),must(f.c.snapshot(u2))}));auto k=f.bind(i,Kind::Move,false,{f.u,u2});auto o1=move(f.u);o1.x=90;auto o2=move(u2);o2.x=110;CHECK(f.send(k,o2,{true,Id(8)}).status==Status::Accepted);CHECK(f.send(k,o1,{true,Id(9)}).status==Status::Accepted);auto p=f.page();CHECK(p.events[0].command_id==p.events[1].command_id);CHECK(*p.events[0].batch_index==1&&*p.events[1].batch_index==0);CHECK(*p.events[0].batch_total==2);CHECK(*p.events[0].order.x==110&&*p.events[1].order.x==90);});
 test("batch revisions are per unit, partial stale is not atomic rollback",[]{F f;auto u2=must(f.c.register_unit(1003,0x5555));auto i=must(f.c.make_issue(Kind::Move,false,{must(f.c.snapshot(f.u)),must(f.c.snapshot(u2))}));auto k=f.bind(i,Kind::Move,false,{f.u,u2});f.ext(move(f.u));CHECK(f.send(k,move(f.u)).status==Status::RejectedStale);CHECK(f.send(k,move(u2)).status==Status::Accepted);CHECK(f.calls==1);});
 test("batch recipient order may follow exact native fanout",[]{F f;auto u2=must(f.c.register_unit(1003,0x5555));auto i=must(f.c.make_issue(Kind::Move,false,{must(f.c.snapshot(f.u)),must(f.c.snapshot(u2))}));auto k=f.bind(i,Kind::Move,false,{u2,f.u});f.send(k,move(f.u));CHECK(*f.page().events[0].batch_index==1);});
 test("engine sequence wrap/gaps do not define identity",[]{F f;auto a=f.ext(move(f.u),{true,Id(0xffffffff)}),b=f.ext(move(f.u),{true,Id(0)});CHECK(*a.engine_seq==0xffffffff&&*b.engine_seq==0);CHECK(b.revision==a.revision+1);});
 test("fresh issue after append uses fresh revision",[]{F f;f.ext(move(f.u,true));auto k=f.own();CHECK(f.send(k,move(f.u)).status==Status::Accepted);CHECK(f.page().events.back().revision==2);});
 test("future revision cannot be fabricated at issue",[]{F f;auto sn=must(f.c.snapshot(f.u));++sn.revision;CHECK(!f.c.make_issue(Kind::Move,false,{sn}));});
 test("batch counts are absent for unbound observer entries",[]{F f;auto e=f.ext(move(f.u));CHECK(!e.batch_index&&!e.batch_total);});
 test("own halt issuing is deliberately not implemented",[]{F f;CHECK(!f.c.make_issue(Kind::Halt,false,{must(f.c.snapshot(f.u))}));});
 test("halt cannot invent an engine sequence",[]{F f;CHECK(!f.c.observe_external(halt(f.u),{true,Id(0)}));CHECK(f.c.fault()==Error::NativeOutcomeInvalid);});
 test("NaN geometry is invalid, not forwarded by own gate",[]{F f;auto k=f.own();auto o=move(f.u);o.x=std::numeric_limits<float>::quiet_NaN();CHECK(f.send(k,o).status==Status::RejectedMetadata);CHECK(f.calls==0);});
 test("attack payload preserves raw flags and pointer",[]{F f;auto k=f.own(Kind::Attack,true);auto o=attack(f.u,true);o.raw71=2;o.raw72=3;o.raw78=4;CHECK(f.send(k,o,{true,Id(12)}).status==Status::Accepted);auto e=f.page().events[0];CHECK(e.order.target_root==o.target_root&&*e.order.raw70==1&&*e.order.raw71==2&&*e.order.raw78==4);});
 test("native exception is indeterminate not zero-side-effect rejection",[]{F f;auto k=f.own();int effects=0;auto r=f.c.dispatch_owned(k,move(f.u),[&]()->NativeOutcome{++effects;throw std::runtime_error("fixture");});CHECK(r.native_called&&r.status==Status::Indeterminate&&effects==1);CHECK(!f.c.issue_enabled());CHECK(f.c.fault()==Error::NativeException);});
 test("nested owned dispatch latches fault before second original",[]{F f;auto a=f.own(),b=f.own();int effects=0;auto r=f.c.dispatch_owned(a,move(f.u),[&]{++effects;CHECK(f.send(b,move(f.u)).status==Status::RejectedFault);return NativeOutcome{true,Id(0)};});CHECK(r.status==Status::Indeterminate&&effects==1&&f.calls==0);});
 test("reentrant external observation preserved, own call indeterminate",[]{F f;auto k=f.own();auto r=f.c.dispatch_owned(k,move(f.u),[&]{f.ext(move(f.u),{true,Id(9)});return NativeOutcome{true,Id(10)};});CHECK(r.status==Status::Indeterminate&&r.native_called);CHECK(must(f.c.snapshot(f.u)).revision==1);CHECK(f.page().events[0].source==Source::Unknown);CHECK(!f.c.issue_enabled());});
 test("lifecycle cannot clear in-flight native pointers",[]{F f;auto k=f.own();auto r=f.c.dispatch_owned(k,move(f.u),[&]{CHECK(f.c.end_battle(f.epoch)==Error::Reentrant);CHECK(f.c.retire_unit(f.u)==Error::Reentrant);return NativeOutcome{true,Id(0)};});CHECK(r.status==Status::Indeterminate);});
 test("contradictory native return is not accepted",[]{F f;auto k=f.own();CHECK(f.send(k,move(f.u),{false,Id(7)}).status==Status::Indeterminate);CHECK(f.c.fault()==Error::NativeOutcomeInvalid);});
 test("external still recorded after gate fault",[]{F f;auto k=f.own();f.c.dispatch_owned(k,move(f.u),[]()->NativeOutcome{throw std::runtime_error("fixture");});auto e=f.ext(move(f.u));CHECK(e.status==Status::Accepted&&e.source==Source::Unknown);});
 test("explicit disabled gate does not call original",[]{F f;auto k=f.own();CHECK(f.c.set_issue_enabled(false)==Error::Ok);CHECK(f.send(k,move(f.u)).status==Status::RejectedDisabled);CHECK(f.calls==0);});
 test("cross battle handles never become valid again",[]{F f;auto k=f.own();auto oldview=f.v;CHECK(f.c.end_battle(f.epoch)==Error::Ok);auto e=must(f.c.begin_battle());CHECK(e!=f.epoch);CHECK(!f.c.resolve(oldview,0,16));CHECK(f.send(k,move(f.u)).status==Status::RejectedUnbound);CHECK(!f.c.issue_enabled());});
 test("old producer scope cannot mark new battle packet",[]{F f;auto i=f.issue(f.u);auto scope=f.c.own_scope(i);f.c.end_battle(f.epoch);must(f.c.begin_battle());auto u=must(f.c.register_unit(1002,0x12340000));auto s=must(f.c.open_stream(0x2000,100));CHECK(!f.c.commit_packet(s,0,16,Kind::Move,false,{u}));CHECK(f.c.fault()==Error::ThreadScope);});
 test("pagination cursor uses last returned not newest",[]{F f;for(int i=0;i<140;++i)f.ext(move(f.u),{true,Id(i)});auto a=f.page(0,64),b=f.page(a.next_after,64),c=f.page(b.next_after,64);CHECK(a.events.size()==64&&b.events.size()==64&&c.events.size()==12);CHECK(a.next_after==64&&a.newest==140);CHECK(c.next_after==140);});
 test("ack cannot skip undelivered prefix",[]{F f;for(int i=0;i<5;++i)f.ext(move(f.u));CHECK(f.c.acknowledge(f.epoch,5)==Error::Invalid);f.page(3,2);CHECK(f.c.acknowledge(f.epoch,5)==Error::Invalid);f.page(0,5);CHECK(f.c.acknowledge(f.epoch,5)==Error::Ok);CHECK(f.c.acknowledge(f.epoch,4)==Error::Invalid);});
 test("acknowledged journal reuse does not poison gate",[]{Limits l;l.journal=2;F f(l);f.ext(move(f.u));f.ext(move(f.u));auto p=f.page();CHECK(f.c.acknowledge(f.epoch,p.next_after)==Error::Ok);auto k=f.own();CHECK(f.send(k,move(f.u)).status==Status::Accepted);CHECK(f.c.issue_enabled());CHECK(f.page(2).events.size()==1);});
 test("unread journal full blocks own side effect",[]{Limits l;l.journal=2;F f(l);auto k=f.own();f.ext(move(f.u));f.ext(move(f.u));auto fresh=f.own();CHECK(f.send(fresh,move(f.u)).status==Status::RejectedFault);CHECK(f.calls==0);CHECK(f.c.fault()==Error::JournalGap);(void)k;});
 test("journal overflow external observation retained with gap",[]{Limits l;l.journal=2;F f(l);for(int i=0;i<4;++i)f.ext(move(f.u));auto p=f.page();CHECK(p.gap&&p.events.size()==2&&p.oldest==3&&p.newest==4&&p.dropped==2);CHECK(!f.c.issue_enabled());CHECK(f.c.set_issue_enabled(true)==Error::JournalGap);});
 test("empty page does not invent progress",[]{F f;auto p=f.page();CHECK(p.events.empty()&&p.next_after==0&&p.newest==0);CHECK(!f.c.read(f.epoch,1,64));CHECK(!f.c.read(f.epoch,0,0));CHECK(!f.c.read(f.epoch,0,65));});
 test("stream retire releases bounded identities, never reuses generation",[]{Limits l;l.packets=1;l.issues=1;F f(l);auto k=f.own();f.send(k,move(f.u));CHECK(f.c.retire_stream(f.s)==Error::Ok);f.s=must(f.c.open_stream(0x2000,0x5000));f.offset=0;auto k2=f.own();CHECK(k.generation!=k2.generation);CHECK(f.send(k2,move(f.u)).status==Status::Accepted);});
 test("registry capacity fails closed, not eviction",[]{Limits l;l.packets=1;F f(l);auto a=f.own();auto i=f.issue(f.u);{auto scope=f.c.own_scope(i);CHECK(!f.c.commit_packet(f.s,16,16,Kind::Move,false,{f.u}));}CHECK(f.c.fault()==Error::Capacity);CHECK(f.send(a,move(f.u)).status==Status::RejectedFault);CHECK(f.calls==0);});
 test("counter exhaustion never silently wraps",[]{Limits l;l.max_counter=3;F f(l);f.ext(move(f.u));f.ext(move(f.u));f.ext(move(f.u));CHECK(!f.c.observe_external(move(f.u),{true,Id(0)}));CHECK(f.c.fault()==Error::CounterExhausted);CHECK(must(f.c.snapshot(f.u)).revision==3);});
 test("scope cancelled after bind stays a tombstone",[]{F f;auto i=f.issue(f.u);auto k=f.bind(i);f.c.cancel_issue(i);CHECK(f.send(k,move(f.u)).status==Status::RejectedCancelled);CHECK(f.send(k,move(f.u)).status==Status::RejectedDuplicate);CHECK(f.calls==0);});
 test("serialized compare-call-commit excludes concurrent observer update",[]{F f;auto k=f.own();std::promise<void> inside, release, attempted;auto ready=inside.get_future();auto go=release.get_future();auto attempt=attempted.get_future();std::atomic<bool> finished{false};DispatchResult result;std::thread a([&]{result=f.c.dispatch_owned(k,move(f.u),[&]{inside.set_value();go.wait();return NativeOutcome{true,Id(0)};});});ready.wait();std::thread b([&]{attempted.set_value();auto r=f.c.dispatch_external(move(f.u),[&]{finished=true;return NativeOutcome{true,Id(1)};});CHECK(r.native_outcome.accepted);});attempt.wait();CHECK(!finished.load());release.set_value();a.join();b.join();CHECK(result.status==Status::Accepted);auto p=f.page();CHECK(p.events.size()==2&&p.events[0].source==Source::OurController&&p.events[1].source==Source::Unknown&&p.events[1].revision==2);});
 test("external native path runs even before battle",[]{IdentityGate c;int calls=0;auto r=c.dispatch_external(move({1,1}),[&]{++calls;return NativeOutcome{true,Id(0)};});CHECK(calls==1&&r.native_outcome.accepted&&r.observer_error==Error::Inactive);});
 test("external native path runs even when gate disabled",[]{F f;f.c.set_issue_enabled(false);int calls=0;auto r=f.c.dispatch_external(move(f.u),[&]{++calls;return NativeOutcome{true,Id(0)};});CHECK(calls==1&&r.native_outcome.accepted&&r.observer_error==Error::Ok);CHECK(f.page().events[0].source==Source::Unknown);});
 test("external native rejection returned unchanged",[]{F f;auto r=f.c.dispatch_external(move(f.u),[]{return NativeOutcome{false,{}};});CHECK(!r.native_outcome.accepted&&r.observer_error==Error::Ok);CHECK(must(f.c.snapshot(f.u)).revision==0);});
 test("external exception rethrown with gate disabled",[]{F f;bool thrown=false;try{f.c.dispatch_external(move(f.u),[]()->NativeOutcome{throw std::runtime_error("native");});}catch(const std::runtime_error&){thrown=true;}CHECK(thrown&&f.c.fault()==Error::NativeException&&!f.c.issue_enabled());});
 test("nested external mutation retained, outer owned status indeterminate",[]{F f;auto k=f.own();int calls=0;auto r=f.c.dispatch_owned(k,move(f.u),[&]{auto e=f.c.dispatch_external(move(f.u),[&]{++calls;return NativeOutcome{true,Id(10)};});CHECK(e.native_outcome.accepted);return NativeOutcome{true,Id(11)};});CHECK(calls==1&&r.status==Status::Indeterminate&&r.native_outcome&&r.native_outcome->accepted);CHECK(f.c.fault()==Error::Reentrant);});
 test("invalid external recipient cannot leave owned gate armed",[]{F f;auto e=f.c.dispatch_external(move({999,999}),[]{return NativeOutcome{true,Id(2)};});CHECK(e.native_outcome.accepted&&e.observer_error==Error::Missing&&!f.c.issue_enabled());});
 test("randomized 1000 delayed issues never overwrite newer external revision",[]{Limits l;l.journal=8192;l.packets=4096;l.issues=4096;F f(l);std::mt19937 rng(1428);for(int i=0;i<1000;++i){auto k=f.own();bool external=(rng()&1)!=0;int before=f.calls;if(external)f.ext(move(f.u,(rng()&1)!=0));auto r=f.send(k,move(f.u),{true,Id(rng())});CHECK(r.status==(external?Status::RejectedStale:Status::Accepted));CHECK(f.calls-before==(external?0:1));if(f.offset+16>0x5000){f.c.retire_stream(f.s);f.s=must(f.c.open_stream(0x2000,0x5000));f.offset=0;}}});
 std::cout<<"SUMMARY scenarios="<<pass+fail<<" pass="<<pass<<" fail="<<fail<<"\n";
 return fail?1:0;
}
