-- H4-S speed-first waypoint guidance: early allowed turns are semantic SOFT, never physical arrival.
local F=assert(loadfile(assert(arg[2])))().new
local pass,fail=0,0
local function T(n,fn)local ok,e=pcall(fn);if ok then pass=pass+1;print("PASS "..n)else fail=fail+1;print("FAIL "..n.." :: "..tostring(e))end end
local function count(f,x)
 local n=0;for _,s in ipairs(f.logs)do if s:find("] "..x.." uid=1001 ",1,true) then n=n+1 end end;return n
end
local function safe(f)
 for _,s in ipairs(f.logs)do assert(not s:find("CONTROLLER_FAIL",1,true),s) end
end
local function start(x,z,w)
 local f=F({debug_source=true,width=w or 20});f:start()
 f:emit("MOVE",false,100,0);f:emit("MOVE",true,x,z)
 f:tick(100,0,0);f:tick(200,60,0)
 return f
end
T("H4S-01 early 90 corner actually ISSUES MOVE while still moving, soft ACK is not measured arrival",function()
 local f=start(100,100,40)
 assert(f.issued==1,"no proactive 90 steering despite original SC1 window")
 assert(f:has("H4_SOFT_CORNER_ISSUE"),"soft permission not certified")
 assert(not f:has("ACTION_COMPLETE"),"pre-ACK credit")
 f:deliver();f:tick(300,60,0)
 assert(count(f,"TRANSITION_EDGE_COMMITTED")==1)
 assert(f:has("reason=H4_SOFT_WAYPOINT_ACCEPTED"),"soft guidance requires separate semantic reason")
 assert(not f:has("reason=ROUTE_NODE_REACHED"),"do not counterfeit physical arrival")
 assert(not f:has("ROUTE_OBLIGATION_TRANSFERRED"),"waived soft corner must not become impossible debt")
 safe(f)
end)
T("H4S-02 180 turnback gets old SC1 early steering window, but cannot double commit",function()
 local f=start(0,0,20)
 assert(f.issued==1,"180 SC1 early turn not restored")
 assert(f:has("H4_SOFT_CORNER_ISSUE"))
 f:deliver();f:tick(300,60,0)
 assert(count(f,"TRANSITION_EDGE_COMMITTED")==1)
 assert(count(f,"H4_SOFT_CORNER_COMMITTED")==1)
 f:tick(400,60,0)
 assert(count(f,"TRANSITION_EDGE_COMMITTED")==1,"duplicate transition")
 safe(f)
end)
T("H4S-03 collinear PATH_SAFE still registers payable debt",function()
 local f=start(200,0,20)
 assert(f.issued==1)
 f:deliver();f:tick(300,60,0)
 assert(f:has("ROUTE_OBLIGATION_TRANSFERRED"))
 assert(not f:has("reason=H4_SOFT_WAYPOINT_ACCEPTED"))
 f:tick(400,105,0)
 assert(f:has("ROUTE_OBLIGATION_SATISFIED"))
 safe(f)
end)
T("H4S-04 5-meter successor short leg cannot be swallowed far before corner",function()
 local f=F({debug_source=true,width=4});f:start()
 f:emit("MOVE",false,100,0);f:emit("MOVE",true,100,5)
 f:tick(100,0,0);f:tick(200,85,0)
 assert(f.issued==0,"short successor overwritten before its turn envelope")
 safe(f)
end)
T("H4S-05 existing prior unpaid debt blocks unsafe lateral turn",function()
 local f=F({debug_source=true,width=4});f:start()
 f:emit("MOVE",false,100,0);f:emit("MOVE",true,120,0);f:emit("MOVE",true,120,40)
 f:tick(100,0,0);f:tick(200,80,0);assert(f.issued==1)
 f:deliver();f:tick(300,80,0)
 assert(f:has("ROUTE_OBLIGATION_TRANSFERRED"))
 f:tick(400,92,0)
 assert(f.issued==1,"unpaid P1 must not be waived through unrelated P2 soft corner")
 safe(f)
end)
T("H4S-06 failed ACK and no ACK cannot create soft credit",function()
 local f=start(100,100,40);assert(f.issued==1)
 f:tick(300,60,0)
 assert(count(f,"TRANSITION_EDGE_COMMITTED")==0)
 assert(not f:has("reason=H4_SOFT_WAYPOINT_ACCEPTED"))
 local b=F({debug_source=true,width=40,reject_native=true});b:start()
 b:emit("MOVE",false,100,0);b:emit("MOVE",true,100,100)
 b:tick(100,0,0);b:tick(200,60,0);assert(b.issued==1)
 b:deliver();b:tick(300,60,0)
 assert(count(b,"TRANSITION_EDGE_COMMITTED")==0)
 assert(not b:has("reason=H4_SOFT_WAYPOINT_ACCEPTED"))
 safe(f);safe(b)
end)
print("TOTAL "..pass.." PASS "..fail.." FAIL; H4 SOFT CORNER CONTROLLER NOT WH3")
os.exit(fail==0 and 0 or 1)
