local A=assert(loadfile(assert(arg[1])))()
local B=assert(loadfile(assert(arg[2])))()
local count=0
local function T(n,fn)
 local ok,why=pcall(fn)
 if not ok then print("FAIL "..n.." "..tostring(why));os.exit(1) end
 count=count+1;print("PASS "..n)
end
local function fixture(mode)
 local g={remaining=46,threshold=42,stall=false,leg=100,next_leg=90,
 progress=0.54,route_min_progress=0.2,route_mode=mode or "PATH_SAFE",
 route_debt_mode="CLEAR",route_debt_count=0,arrival_sync_margin=5,arrival_brake_ready=true,
 cut_error=0.5,cut_safe_limit=1,cut_tolerance=5,
 corner_window=50,corner_window_base=50,corner_window_early=30,corner_stall_escape=false}
 local reason=mode=="STEERING_CORNER" and "TURN_CORRIDOR_ENTERED" or "PATH_DEVIATION_SAFE_WITH_MARGIN"
 local event={exact_current_execution=true,gen="42",unit_lifetime="1",current_action_id="31",
 successor_action_id="32",current_index=1,successor_index=2,current_kind="MOVE",successor_kind="MOVE",
 sample_ms=500,poll_ms=100,decision={transition_kind="MOVE->MOVE",route_ok=true,
 hard_violation=false,route_reason=reason,issue_window={open=false}},geometry=g}
 local q={exact_native_successor=true,gen="42",unit_lifetime="1",current_action_id="31",
 successor_action_id="32",current_index=1,future_index=2,now_ms=600,observed_step_ms=100}
 local e={previous_sample_ms=400,current_sample_ms=500,previous_remaining=51,
 current_remaining=46,ground_distance=5}
 local timing={proximity=1,stall_distance=8,lead_cap=70,brake_extra=3}
 local c=A.capture(event);assert(c)
 return c,q,e,timing,event
end
local function go(c,q,e,t)return B.preview(A,c,q,e,t)end
T("B00 path safe ADOPT_ONLY, nonauthoritative",function()
 local c,q,e,t=fixture();local r=go(c,q,e,t)
 assert(r.preview_open and r.zone=="ADOPT_ONLY" and r.authoritative==false)
 assert(r.credit=="REGISTER_ROUTE_OBLIGATION" and r.one_poll_travel==5)
end)
T("B01 steering completion credit",function()
 local c,q,e,t=fixture("STEERING_CORNER");local r=go(c,q,e,t)
 assert(r.preview_open and r.credit=="STEERING_CORNER_HANDOFF")
end)
T("B02 existing ISSUE open remains baseline",function()
 local c,q,e,t,x=fixture();x.decision.issue_window.open=true;c=A.capture(x)
 assert(go(c,q,e,t).zone=="ISSUE_READY")
end)
T("B03 outside one poll never adopted",function()
 local c,q,e,t,x=fixture();x.geometry.remaining=48;c=A.capture(x)
 e.current_remaining=48;e.previous_remaining=53
 assert(go(c,q,e,t).reason=="OUTSIDE_ONE_POLL_TIMING_BAND")
end)
T("B04 route_not_legal blocks",function()
 local c,q,e,t,x=fixture();x.decision.route_ok=false;c=A.capture(x)
 assert(not go(c,q,e,t).preview_open)
end)
T("B05 future skip and wrong action identity block",function()
 local c,q,e,t=fixture();q.future_index=3;assert(go(c,q,e,t).zone=="HARD_BLOCK")
 q.future_index=2;q.successor_action_id="other";assert(not go(c,q,e,t).preview_open)
end)
T("B06 stale cached poll blocks",function()
 local c,q,e,t=fixture();q.now_ms=601;assert(not go(c,q,e,t).preview_open)
end)
T("B07 stopped or moving away blocks",function()
 local c,q,e,t=fixture();e.previous_remaining=46;assert(not go(c,q,e,t).preview_open)
 e.previous_remaining=41;assert(not go(c,q,e,t).preview_open)
end)
T("B08 sample time must align cache",function()
 local c,q,e,t=fixture();e.previous_sample_ms=300;assert(not go(c,q,e,t).preview_open)
 e.previous_sample_ms=400;e.current_sample_ms=501;assert(not go(c,q,e,t).preview_open)
end)
T("B09 G1 sample and measurement required",function()
 local c,q,e,t,x=fixture();x.geometry.arrival_brake_ready=false;c=A.capture(x)
 assert(not go(c,q,e,t).preview_open)
 x.geometry.arrival_brake_ready=true;x.geometry.arrival_sync_margin=15;c=A.capture(x)
 assert(not go(c,q,e,t).preview_open)
end)
T("B10 steering corridor cannot expand",function()
 local c,q,e,t,x=fixture("STEERING_CORNER");x.geometry.corner_window=45;c=A.capture(x)
 assert(not go(c,q,e,t).preview_open)
end)
T("B11 short next leg caps steering",function()
 local c,q,e,t,x=fixture("STEERING_CORNER");x.geometry.next_leg=30;c=A.capture(x)
 assert(not go(c,q,e,t).preview_open)
end)
T("B12 SC4 stall proof is required",function()
 local c,q,e,t,x=fixture("STEERING_CORNER");x.decision.route_reason="TURN_CORRIDOR_STALL_ESCAPE";c=A.capture(x)
 assert(not go(c,q,e,t).preview_open)
 x.geometry.corner_stall_escape=true;c=A.capture(x);assert(go(c,q,e,t).preview_open)
end)
T("B13 PATH_SAFE cut error and short legs",function()
 local c,q,e,t,x=fixture();x.geometry.cut_error=2;c=A.capture(x)
 assert(not go(c,q,e,t).preview_open)
 x.geometry.cut_error=.5;x.geometry.next_leg=.3;x.geometry.cut_safe_limit=2;c=A.capture(x)
 assert(not go(c,q,e,t).preview_open)
end)
T("B14 SC3 debt retained and snapshot frozen",function()
 local c,q,e,t,x=fixture();x.geometry.route_debt_mode="SOFT_PRESERVED"
 x.geometry.route_debt_count=2;x.geometry.route_debt_error=1;x.geometry.route_debt_limit=1.5;c=A.capture(x)
 local r=go(c,q,e,t);assert(r.preview_open and r.preserve_prior_debt)
 r.geometry.route_debt_error=999;assert(c.geometry.route_debt_error==1)
end)
T("B15 SC3 debt deviation blocks",function()
 local c,q,e,t,x=fixture();x.geometry.route_debt_mode="SOFT_PRESERVED"
 x.geometry.route_debt_count=1;x.geometry.route_debt_error=2;x.geometry.route_debt_limit=1;c=A.capture(x)
 assert(not go(c,q,e,t).preview_open)
end)
T("B16 hard debt and insufficient progress block",function()
 local c,q,e,t,x=fixture();x.geometry.route_debt_mode="HARD";c=A.capture(x)
 assert(not go(c,q,e,t).preview_open)
 x.geometry.route_debt_mode="CLEAR";x.geometry.progress=.1;c=A.capture(x)
 assert(not go(c,q,e,t).preview_open)
end)
T("B17 spoofed larger sync never widens issue",function()
 local c,q,e,t,x=fixture();x.geometry.arrival_sync_margin=20;c=A.capture(x)
 assert(not go(c,q,e,t).preview_open and not c.issue_open)
end)
T("B18 semantic_done but issue closed is contradictory",function()
 local c,q,e,t,x=fixture();x.semantic_done=true;c=A.capture(x)
 assert(not go(c,q,e,t).preview_open)
end)
T("B19 shared issue frontier contradiction fails closed",function()
 local c,q,e,t,x=fixture();x.geometry.remaining=41;c=A.capture(x)
 e.current_remaining=41;e.previous_remaining=46
 assert(go(c,q,e,t).reason=="SHARED_ISSUE_WINDOW_CONTRADICTION")
end)
T("B20 existing PATH_SAFE tolerance remains strict",function()
 local c,q,e,t,x=fixture();x.geometry.cut_safe_limit=10;x.geometry.cut_tolerance=3;c=A.capture(x)
 assert(not go(c,q,e,t).preview_open)
end)
T("B21 invalid legacy CFG timing fails closed",function()
 local c,q,e,t=fixture();t.proximity=nil;assert(not go(c,q,e,t).preview_open)
end)
T("B22 missing post-entry motion cannot authorize",function()
 local c,q,e,t=fixture();e.ground_distance=nil;assert(not go(c,q,e,t).preview_open)
end)
T("B23 ground motion bounds radial travel",function()
 local c,q,e,t=fixture();e.ground_distance=4;assert(not go(c,q,e,t).preview_open)
end)
T("B24 stall-only legacy timing frontier",function()
 local c,q,e,t,x=fixture();x.geometry.threshold=5;x.geometry.stall=true;c=A.capture(x)
 t.stall_distance=42;t.lead_cap=20
 assert(go(c,q,e,t).zone=="ADOPT_ONLY")
end)
T("B25 stall-only frontier absent without stall",function()
 local c,q,e,t,x=fixture();x.geometry.threshold=5;x.geometry.stall=false;c=A.capture(x)
 t.stall_distance=42;t.lead_cap=20
 assert(not go(c,q,e,t).preview_open)
end)
T("B26 steering window max composition proof",function()
 local c,q,e,t,x=fixture("STEERING_CORNER");x.geometry.corner_window=51;c=A.capture(x)
 assert(not go(c,q,e,t).preview_open)
end)
T("B27 current point must already be inside steering corridor",function()
 local c,q,e,t,x=fixture("STEERING_CORNER");x.geometry.corner_window=45;x.geometry.corner_window_base=45;c=A.capture(x)
 assert(not go(c,q,e,t).preview_open)
end)
print("TOTAL "..count.." PASS 0 FAIL; T2-MOVE-B NONAUTHORITATIVE")
