-- H2-B/C/D post-fix real-controller semantics. H2-A raw red test remains unmodified.
local F=assert(loadfile(assert(arg[2])))().new
local pass,fail=0,0
local function T(name,fn)
 local ok,why=pcall(fn);if ok then pass=pass+1;print("PASS "..name)
 else fail=fail+1;print("FAIL "..name.." :: "..tostring(why)) end
end
local function count(f,tag)
 local n=0;for _,l in ipairs(f.logs) do if l:find("] "..tag.." uid=1001 ",1,true) then n=n+1 end end;return n
end
local function healthy(f)
 for _,s in ipairs(f.logs) do assert(not s:find("CONTROLLER_FAIL",1,true),s) end
end
local function scenario(px,pz,width)
 local f=F({debug_source=true,width=width or 20});f:start()
 f:emit("MOVE",false,100,0)
 f:emit("MOVE",true,px,pz)
 f:tick(100,0,0);f:tick(200,60,0)
 return f
end
T("H2-RT01 proactive U-turn cannot abandon waypoint from x60",function()
 local f=scenario(0,0)
 assert(f.issued==0,"unsafe turnback was sent")
 assert(f:has("H2_ROUTE_ISSUE_BLOCKED"),"route protection invisible")
 assert(count(f,"TRANSITION_EDGE_COMMITTED")==0 and not f:has("STEERING_CORNER_HANDOFF"))
 healthy(f)
end)
T("H2-RT02 90-degree early shortcut cannot invent route credit",function()
 local f=scenario(100,100,40)
 assert(f.issued==0,"unsafe early lateral route issued")
 assert(count(f,"TRANSITION_EDGE_COMMITTED")==0)
 assert(not f:has("STEERING_CORNER_HANDOFF"))
 healthy(f)
end)
T("H2-RT03 reach-boundary 90-degree turn commits with observed route satisfaction",function()
 local f=F({debug_source=true,width=40});f:start()
 f:emit("MOVE",false,100,0);f:emit("MOVE",true,100,100)
 f:tick(100,0,0);f:tick(200,98,0)
 assert(f.issued==1,"safe near-waypoint turn blocked")
 f:deliver();f:tick(300,98,0)
 assert(count(f,"TRANSITION_EDGE_COMMITTED")==1)
 assert(f:has("ACTION_COMPLETE") and not f:has("reason=STEERING_CORNER_HANDOFF"))
 assert(not f:has("ROUTE_OBLIGATION_TRANSFERRED"),"already paid waypoint got debt")
 healthy(f)
end)
T("H2-RT04 forward early MOVE preserves route debt until observed crossing",function()
 local f=scenario(200,0)
 assert(f.issued==1,"legal forward handoff blocked")
 f:deliver();f:tick(300,60,0)
 assert(count(f,"TRANSITION_EDGE_COMMITTED")==1)
 assert(count(f,"ROUTE_OBLIGATION_TRANSFERRED")==1)
 assert(not f:has("reason=STEERING_CORNER_HANDOFF"))
 f:tick(400,105,0)
 assert(count(f,"ROUTE_OBLIGATION_SATISFIED")==1,"P100 unpaid after true crossing")
 healthy(f)
end)
T("H2-RT05 no uncommitted credit and rejected ACK remains inert",function()
 local f=scenario(200,0)
 assert(f.issued==1)
 f:tick(300,65,0)
 assert(count(f,"TRANSITION_EDGE_COMMITTED")==0 and count(f,"ROUTE_OBLIGATION_TRANSFERRED")==0)
 healthy(f)
 local bad=F({debug_source=true,reject_native=true});bad:start()
 bad:emit("MOVE",false,100,0);bad:emit("MOVE",true,200,0)
 bad:tick(100,0,0);bad:tick(200,60,0);assert(bad.issued==1)
 bad:deliver();bad:tick(300,60,0)
 assert(count(bad,"TRANSITION_EDGE_COMMITTED")==0 and count(bad,"ROUTE_OBLIGATION_TRANSFERRED")==0)
 healthy(bad)
end)
T("H2-RT06 135-degree bend and short reverse segment remain protected",function()
 for _,p in ipairs({{30,70},{80,0},{105,0}}) do
  local f=scenario(p[1],p[2])
  if p[1]~=105 then assert(f.issued==0,"premature 135 or reverse") end
  healthy(f)
 end
end)
T("H2-RT07 sequential legal forward edges preserve both outstanding debts",function()
 local f=F({debug_source=true,width=4});f:start()
 f:emit("MOVE",false,100,0);f:emit("MOVE",true,120,0);f:emit("MOVE",true,140,0)
 f:tick(100,0,0);f:tick(200,80,0);assert(f.issued==1)
 f:deliver();f:tick(300,80,0)
 assert(count(f,"ROUTE_OBLIGATION_TRANSFERRED")==1)
 f:tick(400,92,0);assert(f.issued==2,"SC3 collinear did not continue")
 f:deliver();f:tick(500,92,0)
 assert(count(f,"ROUTE_OBLIGATION_TRANSFERRED")==2,"both debts must be independent")
 assert(count(f,"ROUTE_OBLIGATION_SATISFIED")==0)
 healthy(f)
end)
print("TOTAL "..pass.." PASS "..fail.." FAIL; H2 CONTROLLER ONLY, NOT WH3")
os.exit(fail==0 and 0 or 1)
