from __future__ import annotations
import argparse, hashlib, struct
from pathlib import Path

EXPECTED_MINHOOK_SHA256 = "e9c9fa622f5220b4dd5162b817b9295c53a7978a7bd0b656eac0d29a1106e8ea"
BRIDGE_VERSION = b"0.5.1-per-kind-calibration"
BRIDGE_EXPORT = b"luaopen_wh3_native_bridge"

def sha256(data: bytes) -> str:
    return hashlib.sha256(data).hexdigest()

def payload_lua(label: str, data: bytes) -> bytes:
    h = sha256(data)
    lines = [
        "-- Better Shift Command embedded native payload.",
        "-- Generated by build_selfcontained_pack.py; do not hand-edit.",
        f"-- payload={label}",
        f"-- size={len(data)}",
        f"-- sha256={h}",
        "return table.concat({",
    ]
    for off in range(0, len(data), 4096):
        chunk = data[off:off+4096]
        enc = ''.join(f"\\{b:03d}" for b in chunk)
        lines.append('"' + enc + '",')
    lines.append('})')
    lines.append('')
    return '\n'.join(lines).encode('ascii')

def make_pfh5(files: list[tuple[str, bytes]]) -> bytes:
    # WH3 PFH5 type=3. File index entries are: u32 size, u8 flag(0), UTF-8 path NUL.
    index = bytearray()
    for name, data in files:
        raw_name = name.encode('utf-8')
        if b'\x00' in raw_name:
            raise ValueError('NUL in pack path')
        index += struct.pack('<I', len(data))
        index += b'\x00'
        index += raw_name + b'\x00'
    header = bytearray()
    header += b'PFH5'
    header += struct.pack('<I', 3)
    header += struct.pack('<I', 0)
    header += struct.pack('<I', 0)
    header += struct.pack('<I', len(files))
    header += struct.pack('<I', len(index))
    header += struct.pack('<I', 0)
    assert len(header) == 0x1c
    return bytes(header + index) + b''.join(data for _, data in files)

def parse_pfh5(data: bytes):
    if data[:4] != b'PFH5': raise ValueError('bad PFH5')
    count = struct.unpack_from('<I', data, 0x10)[0]
    idx_size = struct.unpack_from('<I', data, 0x14)[0]
    pos = 0x1c
    meta=[]
    for _ in range(count):
        size=struct.unpack_from('<I',data,pos)[0];pos+=4
        flag=data[pos];pos+=1
        z=data.index(0,pos);name=data[pos:z].decode('utf-8');pos=z+1
        meta.append((name,size,flag))
    if pos != 0x1c+idx_size: raise ValueError('index size mismatch')
    out=[]
    for name,size,flag in meta:
        raw=data[pos:pos+size];pos+=size;out.append((name,raw,flag))
    if pos != len(data): raise ValueError('trailing/short data')
    return out

def main():
    ap=argparse.ArgumentParser()
    ap.add_argument('--bridge', type=Path, required=True)
    ap.add_argument('--minhook', type=Path, required=True)
    ap.add_argument('--controller-template', type=Path, required=True)
    ap.add_argument('--license', type=Path, required=True)
    ap.add_argument('--out', type=Path, required=True)
    args=ap.parse_args()
    bridge=args.bridge.read_bytes(); minhook=args.minhook.read_bytes()
    if not bridge.startswith(b'MZ'): raise SystemExit('Bridge is not a PE/DLL')
    if BRIDGE_VERSION not in bridge: raise SystemExit('Bridge version string not found: expected 0.5.1-per-kind-calibration')
    if BRIDGE_EXPORT not in bridge: raise SystemExit('Bridge Lua export string not found')
    mh=sha256(minhook)
    if mh != EXPECTED_MINHOOK_SHA256: raise SystemExit(f'MinHook SHA256 mismatch: {mh}')
    bh=sha256(bridge)
    controller=args.controller_template.read_text(encoding='utf-8')
    controller=controller.replace('@@BRIDGE_SIZE@@', str(len(bridge))).replace('@@BRIDGE_SHA256@@', bh)
    if '@@BRIDGE_' in controller: raise SystemExit('Unresolved controller template token')
    controller_bytes=controller.replace('\r\n','\n').encode('utf-8')
    notice=(
        "Better Shift Command v1.0.1\n"
        "Native Bridge v0.5.1-per-kind-calibration is embedded and materialized at battle load.\n"
        f"Bridge SHA256: {bh}\n"
        f"MinHook SHA256: {mh}\n"
        "MinHook is distributed under its upstream license included in this pack.\n"
    ).encode('utf-8')
    files=[
        ('script\\battle\\mod\\better_shift_command.lua', controller_bytes),
        ('script\\better_shift_command\\bin\\bridge_Windows_NT-x64.lua', payload_lua('wh3_native_bridge.dll', bridge)),
        ('script\\better_shift_command\\bin\\minhook_Windows_NT-x64.lua', payload_lua('minhook.x64.dll', minhook)),
        ('script\\better_shift_command\\licenses\\MINHOOK_LICENSE.txt', args.license.read_bytes()),
        ('script\\better_shift_command\\licenses\\THIRD_PARTY_NOTICES.txt', notice),
    ]
    pack=make_pfh5(files)
    # Offline round-trip validation: extract payload Lua source and verify exact controller bytes/metadata.
    parsed=parse_pfh5(pack)
    if len(parsed)!=5: raise SystemExit('Pack round-trip file count mismatch')
    if parsed[0][1] != controller_bytes: raise SystemExit('Controller round-trip mismatch')
    args.out.parent.mkdir(parents=True,exist_ok=True)
    args.out.write_bytes(pack)
    print(f'PACK={args.out}')
    print(f'PACK_SHA256={sha256(pack)}')
    print(f'BRIDGE_SHA256={bh}')
    print(f'BRIDGE_SIZE={len(bridge)}')
    print(f'MINHOOK_SHA256={mh}')

if __name__=='__main__': main()
